services:
  # tailscale:
  #   container_name: tailscale
  #   image: tailscale/tailscale:latest
  #   restart: unless-stopped
  #   network_mode: host
  #   cap_add:
  #     - NET_ADMIN
  #   devices:
  #     - /dev/net/tun:/dev/net/tun
  #   ports:
  #     - 9002:9002
  #   env_file:
  #     - .env
  #   environment:
  #     - TS_AUTHKEY=${TS_AUTHKEY}
  #     - TS_ACCEPT_DNS=true
  #     - TS_STATE_DIR=/var/lib/tailscale
  #     - TS_HOSTNAME=jojo-pve
  #     - TS_USERSPACE=false
  #     - TS_LOCAL_ADDR_PORT=[::]:9002
  #     - TS_ENABLE_METRICS=true
  #     - TS_ROUTES=${TS_ROUTES}
  #     - TS_EXTRA_ARGS=--accept-routes
  #   volumes:
  #     - /docker/tailscale/state:/var/lib/tailscale

  hawser:
    container_name: hawser
    image: ghcr.io/finsys/hawser:latest
    restart: unless-stopped
    ports:
      - 2376:2376 # Or use Edge mode (no ports)
    env_file:
      - .env
    environment:
      - PORT=2376
      - DOCKER_SOCKET=/var/run/docker.sock
      - TOKEN=${HAWSER_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Access host Docker
      - /docker/hawser/stack:/data/stack # For stack files/volumes
